version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - API_URL=http://server:8000
    volumes:
      - ../src/:/app/src
    networks:
      - sam-network

  server:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    deploy:
        resources:
          reservations:
            devices: #add additional device id's if you have more GPUs in your system
             - driver: nvidia
               device_ids: ['0']
               capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ../:/app/scripts
    networks:
      - sam-network

networks:
  sam-network:
    external:
      name: sam-network